#!/bin/sh

# Build the configuration file
if [ ! -f $NHOS_CONFIG_FILE ]; then cat <<EOF > $NHOS_CONFIG_FILE
{
	"rig": {
		"btc": "$BTC_ADDR",
		"worker": "$WORKER",
		"group": "$GROUP"
	},
}
EOF
fi

case $1 in
	shell) sh;;
	*) nhm_start;;
esac
