#!/bin/sh

bring_image(){
	wget "https://files.nicehash.com/nhminer/nhos/nhos-$NHOS_VERSION/image/nhos-$NHOS_VERSION.img.gz" -O nhos.img.gz
	gunzip nhos.img.gz
}

convert_image(){
	truncate nhos.img -s "$1"
	sgdisk nhos.img -e
	qemu-img convert nhos.img -O vpc -o subformat=fixed,force_size nhos.vhdx
}

if [ -f nhos.img ]; then
	convert_image 702545408
else
	if [ -f nhos.img.gz ]; then
		bring_image
	fi
	convert_image 702545408
fi
